apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: demo-app
          image: zkdlu/deployment-demo:v1
          ports:
            - containerPort: 8080
